const { defineConfig } = require("@vue/cli-service");
module.exports = defineConfig({
  transpileDependencies: true,
  publicPath: "./",
  outputDir: "dist",
  // assertDir: "",
  indexPath: "index.html",
  pages: {
    music: {
      entry: "src/views/music/music.js",
      template: "public/music.html",
      filename: "music.html",
      title: "Music",
      chunks: ["chunk-vendors", "chunk-common", "music"],
    },
    shop: {
      entry: "src/views/shop/shop.js",
      template: "public/shop.html",
      filename: "shop.html",
      title: "Shop",
      chunks: ["chunk-vendors", "chunk-common", "shop"],
    },
    activity: {
      entry: "src/views/activity/activity.js",
      template: "public/activity.html",
      filename: "activity.html",
      title: "Activity",
      chunks: ["chunk-vendors", "chunk-common", "activity"],
    },
    member: {
      entry: "src/views/member/member.js",
      template: "public/member.html",
      filename: "member.html",
      title: "Member",
      chunks: ["chunk-vendors", "chunk-common", "member"],
    },
    creator: {
      entry: "src/views/creator/creator.js",
      template: "public/creator.html",
      filename: "creator.html",
      title: "Creator",
      chunks: ["chunk-vendors", "chunk-common", "creator"],
    },
    login: {
      entry: "src/views/login/login.js",
      template: "public/login.html",
      filename: "login.html",
      title: "Login",
      chunks: ["chunk-vendors", "chunk-common", "login"],
    },
    register: {
      entry: "src/views/register/register.js",
      template: "public/register.html",
      filename: "register.html",
      title: "Register",
      chunks: ["chunk-vendors", "chunk-common", "register"],
    },
    reset: {
      entry: "src/views/reset/reset.js",
      template: "public/reset.html",
      filename: "reset.html",
      title: "Reset",
      chunks: ["chunk-vendors", "chunk-common", "reset"],
    },
    resetPassword: {
      entry: "src/views/resetPassword/resetPassword.js",
      template: "public/resetPassword.html",
      filename: "resetPassword.html",
      title: "ResetPassword",
      chunks: ["chunk-vendors", "chunk-common", "resetPassword"],
    },
    index: {
      entry: "src/main.js",
      template: "public/index.html",
      filename: "index.html",
      title: "iSMusic",
      chunks: ["chunk-vendors", "chunk-common", "index"],
    },
  },
  // devServer: {
  //   port: "8080",
  //   https: true,
  // },
});
